[package]
name = "pmfumeta_server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enet = "0.2.3"
json = "0.12.4"
enum-utils = "0.1.2"
igd = "0.12.0"